### ISSUE TITLE
HOW TO DISABLE ADD BUTTON WHEN MAX_NUM REACHED ?

### ISSUE THREAD

**Issue by sasikumar1978k** [Actionb/mizdb-inlines#3] opened 2023-09-15 08:24 UTC
HOW TO DISABLE ADD BUTTON WHEN MAX_NUM REACHED AND DISABLE DELETE BUTTON WHEN MIN_NUM REACHED

formset_classes = (inlineformset_factory(degree, degreesub, fields=["name",], extra=1 ,max_num=2,min_num=1),)

![Screenshot from 2023-09-15 13-53-42](https://github.com/Actionb/mizdb-inlines/assets/23027374/d3c6e5e5-b659-46e5-b510-e4e6514bad78)

![Screenshot from 2023-09-15 13-54-03](https://github.com/Actionb/mizdb-inlines/assets/23027374/537e62b9-f12f-4e78-9679-732437a98b9c)

**Comment by Actionb** [comment] 2023-09-25 07:38
`max_num` and `min_num` are not enforced. I don't have any forms that require those, so I didn't put in the time and effort to write the logic for it. 

To enforce max and min, you'd have to check the number of forms in the add and delete handlers whenever you add or delete a form. It shouldn't be much work, but I can't tell you when I get around to do it.

**Comment by Actionb** [comment] 2023-10-10 06:49
Duplicate of #1 and #2

**Closed as completed by Actionb** 2023-10-10 06:49 UTC
